/**
 * Cryptographic utilities for InkSocial
 * Handles EIP-712 style signing and verification
 */

import { Logger } from '../utils/logger.js';

export const CryptoService = {
    domain: {
        name: 'InkSocial',
        version: '1',
        chainId: 57073, // Ink Network Mainnet ID
        verifyingContract: '0x0000000000000000000000000000000000000000' // Placeholder
    },

    types: {
        Cast: [
            { name: 'author', type: 'address' },
            { name: 'content', type: 'string' },
            { name: 'timestamp', type: 'uint256' },
            { name: 'channel', type: 'string' }
        ],
        Action: [
            { name: 'actor', type: 'address' },
            { name: 'type', type: 'string' }, // 'like', 'recast', 'follow'
            { name: 'targetHash', type: 'string' },
            { name: 'timestamp', type: 'uint256' }
        ]
    },

    /**
     * Simulates signing a message with a wallet
     * In a real app, this would use window.ethereum.request({ method: 'eth_signTypedData_v4', ... })
     */
    async signTypedData(address, typeName, value) {
        Logger.info(`[Crypto] Requesting signature from ${address} for ${typeName}...`);
        
        // Simulate wallet prompt delay
        await new Promise(r => setTimeout(r, 800));

        // In simulation, we just generate a mock hash as "signature"
        // In reality, this would be a valid EIP-712 signature string
        const mockSignature = '0x' + Array.from({length: 130}, () => Math.floor(Math.random() * 16).toString(16)).join('');
        
        return {
            payload: value,
            signature: mockSignature,
            signer: address
        };
    },

    /**
     * Simulates verifying a signature on the backend
     */
    verify(message, signature, expectedSigner) {
        // In simulation, we assume all signatures generated by our mock signer are valid
        // Real implementation would use ethers.verifyTypedData
        return signature.startsWith('0x') && signature.length === 132;
    }
};
